### ISSUE TITLE
Selecting Date time field gives error

### ISSUE THREAD

**Issue by mjafartp** [nealwon/go-flutter-plugin-sqlite#8]
i was inserted Date time field using Default option in database creation (CURRENTTIMESTAMP) 
But on selecting data after insert gives an error. 

Create query : `CREATE TABLE 'data' ('ID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,'NO' INTEGER, 'SDate' DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, 'LOCALTIME')), 'Customer' TEXT,'guestNo' INTEGER DEFAULT 0);`

```
go-flutter: failed to encode success envelope for method 'query' on channel 'com.tekartik.sqflite', error: invalid type provided to message codec: type time.Time is not supported by StandardMessageCodec
flutter: MissingPluginException(No implementation found for method query on channel com.tekartik.sqflite)
flutter: #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      invokeMethod (package:sqflite/src/sqflite_impl.dart:20:13)
#2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:29:7)
#3      SqfliteDatabaseMixin.invokeMethod (package:sqflite/src/database_mixin.dart:267:15)
#4      SqfliteDatabaseMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/database_mixin.dart:188:43)
#5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:8:34)
<asynchronous suspension>
#6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)
#7      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188:15)
#8      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite/src/database_mixin.dart:374:36)
<asynchronous suspension>
#9      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite/src/database_mixin.dart:307:22)
#10     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
<asynchronous suspension>
#11     SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:303:43)
<asynchronous suspension>
#12     SqfliteDatabaseMixin.txnRawQuery (package:sqflite/src/database_mixin.dart:373:12)
#13     SqfliteDatabaseExecutorMixin.rawQuery (package:sqflite/src/database_mixin.dart:119:15)
```

**Comment by mjafartp** [comment]
also see dependency error 
https://github.com/mattn/go-sqlite3/issues/748
